version: "3.8"
services:
  aspnet-app1:
    build:
      context: ./Project1
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - app-network

  react-app:
    build:
      context: ./ReactProject
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay